Ft/accessibility
guillaumebdx/worldle pull request #4
Opened 2022-02-16 15:39 UTC by k4r1n3

2022-02-18 21:20 UTC, guillaumebdx commented on node_modules/.yarn-integrity
> +{
il ne devrait pas y avoir de dossier node_modules dans ce projet, peux tu le supprimer et commit et push à nouveau stp ?

2022-02-18 21:21 UTC, guillaumebdx requested changes
il ne devrait pas y avoir de dossier node_modules dans ce projet, peux tu le supprimer et commit et push à nouveau stp ?

2022-02-19 09:06 UTC, k4r1n3 commented on node_modules/.yarn-integrity
> +{
Done

2022-02-19 09:08 UTC, k4r1n3 commented
Done

2022-02-21 21:51 UTC, merged